### Numpy - Biblioteca matemática, mais utilizada com Álgebra Linear. Vetores e Matrizes.

In [1]:
#Importação do NumPy
import numpy as np

Estrutura Unidimensional

In [2]:
a1 = np.array(['Spark', 'Hadoop', 'Python', 'R'])

In [3]:
a1

array(['Spark', 'Hadoop', 'Python', 'R'], dtype='<U6')

### Arrays podem ter listas de tipos diferentes

Estruturas Bidimensionais

In [4]:
a2 = np.array([['Altura', 'Largura', 'Profundidade'],[42,78,10]])

In [5]:
a2

array([['Altura', 'Largura', 'Profundidade'],
       ['42', '78', '10']], dtype='<U12')

In [6]:
a3 = np.array([[10,20,30],[40,50,60]])

In [7]:
a3

array([[10, 20, 30],
       [40, 50, 60]])

In [8]:
#Tamanho do array
print(a1.shape)
print(a2.shape)

(4,)
(2, 3)


In [9]:
#Dimensoes do Array
a1.ndim

1

In [10]:
a2.ndim

2

Ausência ou presença de parêntes:

Podemos realizar uma analogia com características e ações. O uso de parênteses reflete uma AÇÂO, enquanto a ausencia, reflete uma caracteristica
    

In [11]:
#O Método max() não funciona com arrays de tipo heterogeneo
a3.max()

60

In [12]:
# Atributo
a2.ndim

2

### Método Arrange

In [13]:
array = np.arange(20)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
# Usando start/end - de 0 a 100 de 10 em 10
array = np.arange(0, 100, 10)

In [15]:
array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

### Criando estruturas de dados com linspace

In [16]:
# Fique atento: A diferença do linspace para o orange é que no orange o ultimo argumento é o incremento,
# e no linspace o último argumento é o número de elementos do vetor (aleatorio)

matriz = np.linspace(0, 10, 20)
matriz

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [18]:
matriz = np.linspace(0,10,5)
matriz

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
matriz = np.linspace(0,5,5)
matriz

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

### Estruturas de Matrizes

In [20]:
#numpy.zeros

matriz = np.zeros((10,10))
matriz

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [21]:
#numpy.ones
matriz = np.ones((2,3))
matriz

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
# numpy.empty produz uma matriz vazia

matriz = np.empty((10,5))
matriz

array([[9.20790189e-312, 1.76875501e-321, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [1.15998412e-028, 4.31603868e-080, 1.94919985e-153,
        1.35717430e+131, 6.01347002e-154],
       [3.24245676e-086, 4.46965623e-033, 7.85914197e-067,
        6.03108754e-154, 9.06853733e-043],
       [8.54510934e-072, 1.03896640e-095, 6.01347002e-154,
        1.79576854e-052, 1.95996717e-062],
       [9.06853733e-043, 6.51825359e-038, 1.05162717e-153,
        7.85915897e-067, 4.04676264e-086],
       [9.73265296e-072, 6.01347002e-154, 5.39555299e-062,
        6.03109330e-154, 5.64057948e-062],
       [3.67199563e-062, 1.08633609e-095, 1.03030888e-071,
        3.61550129e-043, 1.48508498e-076],
       [6.01347176e-154, 4.65700042e-033, 1.05177457e-153,
        1.69054167e-052, 4.85106851e-086],
       [7.49985795e-067, 5.64053869e-062, 4.57669087e-072,
        6.01347002e-154, 1.06239598e-153],
       [3.98472821e+252, 1.06244660e-153, 9.78750380e+199,
        6.97843734e+252

### numpy.tile

In [23]:
np.tile(np.array([[1,2],[3,4],[5,6]]),3)

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6]])

In [24]:
np.tile(np.array([[1,2],[3,4],[5,6]]), (3,6)) #Num de vezes do array na vertical, num de vezes array na hotizontal

array([[1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6]])