In [1]:
#Importação do NumPy
import numpy as np

### Tipagem de Dados

In [2]:
#Podemos passar um tipo para Array por parametro

a = np.array([-10,10,20,30], dtype = 'float')

In [3]:
a

array([-10.,  10.,  20.,  30.])

In [4]:
#A propriedade dtype me retorna o tipo dos elementos do array

a.dtype

dtype('float64')

In [9]:
#Caso eu não passe o tipo para o python, ele definirá automaticamente

b = np.array([-10,10,20,30])

b.dtype

dtype('int32')

In [8]:
b

array([-10,  10,  20,  30])

In [ ]:
d.dtype

In [10]:
#Caso exista um elemento diferente dos demais, o Python irá tipar o array pelo elemento mais especifico.

c = np.array([10,20,30,40.5])
c.dtype

dtype('float64')

In [11]:
#Podemos tambèm ter um tipo string

d = np.array(['Universidade', 'dos', 'Dados'])

In [12]:
d.dtype

dtype('<U12')

In [13]:
#Array do tipo boleano

e = np.array([False, False, True])

In [14]:
e.dtype

dtype('bool')

### Cast de Arrays

In [15]:
f = np.array([-9, 10, 20.7])
f.dtype

dtype('float64')

In [16]:
#Posso realizar um CAST com a função astype()

f.astype(int)

array([-9, 10, 20])

### Criando Arrays com operações aritméticas em tempo de execução

In [17]:
#Aprendemos que a função arange serve para criar um array

array = np.arange(0,5)
array

array([0, 1, 2, 3, 4])

In [18]:
# Podemos criar um array com qualquer operação aritmética

array = np.arange(0, 10) * 10

In [19]:
array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [20]:
# Potencia
array = np.arange(10) ** 2

In [21]:
array

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

### Operações Aritméticas entre Arrays

In [22]:
arrayA = np.arange(0,10)
arrayB = np.arange(0,10)+1

In [23]:
arrayA

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arrayB

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
# Soma
arrayA + arrayB

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [27]:
# Subtração
arrayB - arrayA

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [28]:
# Divisão
arrayA / arrayB

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ,
       0.83333333, 0.85714286, 0.875     , 0.88888889, 0.9       ])

In [29]:
# Multiplicação
arrayA * arrayB

array([ 0,  2,  6, 12, 20, 30, 42, 56, 72, 90])

In [30]:
# Comparação de arrays
arrayA == arrayB

array([False, False, False, False, False, False, False, False, False,
       False])

In [31]:
arrayA > arrayB

array([False, False, False, False, False, False, False, False, False,
       False])

In [32]:
arrayA < arrayB

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [33]:
#Podemos ainda utilizar a tabela verdade para comparar dois arrays utilizando por exemplo a Logica AND

In [34]:
array1 = np.array([True,False,True,False])
array2 = np.array([False,False,True,False])
np.logical_and(array1, array2)

array([False, False,  True, False])

In [35]:
array1 = np.array([True,False,True,False])
array2 = np.array([False,False,True,False])
np.logical_or(array1, array2)

array([ True, False,  True, False])

### Arrays com tamanho diferente

In [36]:
A = np.array([1,2,3,4,5])
B = np.array([1,2,3])

### Não é possivel fazer calculos com arrays de tamanhos diferentes

In [37]:
A * B

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

### Dot Product

In [38]:
A = np.array([2,4,6])
B = np.array([2,2,2])

In [39]:
#Hadmard Product

A * B

array([ 4,  8, 12])

In [40]:
#Dot Product

print(np.dot(A,B))

24


### Cópias de Arrays

In [41]:
A = np.arange(10)

In [42]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
B = A[5:]

In [44]:
B

array([5, 6, 7, 8, 9])

In [45]:
A[:] = 0

In [46]:
B

array([0, 0, 0, 0, 0])

In [47]:
A = np.arange(10)

In [48]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])