In [2]:
import numpy as np

In [3]:
a = [1,2,11,6,8,18,2]

array = np.array(a)

print(type(array))

<class 'numpy.ndarray'>


In [4]:
#Verificando o tamanho do array

print(array.shape)

(7,)


In [5]:
#Primeiro Elemento

array[0]

1

In [6]:
#Elemento do indice 2

array[2]

11

In [7]:
#Ultimo elemento

array[-1]

2

In [9]:
#Trazendo o indice 1 até o 5 (exclusivo)

print(array[1:5])

[ 2 11  6  8]


In [10]:
#Utilizando um passo de 2 em 2

print(array[1:5:2])

[2 6]


In [11]:
#Trazendo com indices negativos.
# -7 representa o primeiro da esquerda e -3 o ultimo elemento a ser trazido (exclusivo)

print(array[-7:-3])

[ 1  2 11  6]


In [12]:
#Indice 3 até o fim

print(array[3:])

[ 6  8 18  2]


In [13]:
#Início até o indice 4

print(a[:4])

[1, 2, 11, 6]


In [14]:
#Invertendo o array - Inicio até o fim, ao passo de -1

array[::-1]

array([ 2, 18,  8,  6, 11,  2,  1])

In [15]:
#Copiando um array por referencia

b = array[:]
print(b)

[ 1  2 11  6  8 18  2]


In [16]:
#Concatenando 2 arrays

x = np.array([2,6,8,4])

y = np.array([11,8,2])

z = np.concatenate([x,y])

print(z)

[ 2  6  8  4 11  8  2]
