In [3]:
import numpy as np

# Operações com Arrays Multidimensionais

### Lembre-se - A notação é sempre LINHA - COLUNA

In [4]:
A = [[1,2,3,4],[5,6,7,8],[10,20,30,40],[50,60,70,80]]

array = np.array(A)

print(array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 20 30 40]
 [50 60 70 80]]


In [5]:
#Primeira Linha
print(array[0])

[1 2 3 4]


In [6]:
#Linha de indice 2
print(array[2])

[10 20 30 40]


In [7]:
#Primeira Linha e última coluna
print(array[0,-1])

4


In [14]:
#Atribuindo um valor a uma posição da matriz

array [0,3] = 9

print(array)

[[ 0  2  3  9]
 [ 9  6  7  8]
 [10 20 30 40]
 [50 60 70 80]]


### Trabalhando com intervalos

In [16]:
#Pegando os numeros centrais

print(array[1:3,1:3])

[[ 6  7]
 [20 30]]


In [17]:
#Trazendo somente a ultima coluna

print(array[:, -1])

[ 9  8 40 80]


In [18]:
#Trazendo somente a ultima linha

print(array[-1,:])

[50 60 70 80]


In [22]:
#Concatenando arrays multidimensionais

A = np.array([[1,2],[3,4]])
B = np.array([[5,6]])

C = np.concatenate((A, B))

print(C)

[[1 2]
 [3 4]
 [5 6]]
