In [1]:
#Matrizes são objetos ESTRITAMENTE bidimensionais, o que torna mais facil as operações aritmáticas

In [2]:
import numpy as np

In [3]:
A = np.matrix([[1,2],[3,4]])

B = np.matrix([[5,3],[8,7]])

Z = np.array([
    [[2,6], [8,4]],
    [[2,6], [8,4]],
    [[2,6], [8,4]]
])

Y = np.array([2,6,8,4])

In [4]:
Z = np.matrix([
    [[2,6], [8,4]],
    [[2,6], [8,4]],
    [[2,6], [8,4]]
])

ValueError: matrix must be 2-dimensional

In [5]:
print(type(A))

<class 'numpy.matrix'>


In [6]:
print(type(Z))

<class 'numpy.ndarray'>


In [7]:
print(type(Y))

<class 'numpy.ndarray'>


In [8]:
print(A)

[[1 2]
 [3 4]]


In [9]:
print(Z)

[[[2 6]
  [8 4]]

 [[2 6]
  [8 4]]

 [[2 6]
  [8 4]]]


In [10]:
print(Y)

[2 6 8 4]


In [11]:
Z.shape

(3, 2, 2)

In [12]:
Y.shape

(4,)

### Soma

In [13]:
print(A + B)

[[ 6  5]
 [11 11]]


In [14]:
print(B + 3)

[[ 8  6]
 [11 10]]


### Subtração

In [15]:
print(A-B)

[[-4 -1]
 [-5 -3]]


### Multiplicação

In [17]:
A = np.matrix([[1,2],[3,4]])

print(A)

[[1 2]
 [3 4]]


In [18]:
#Arrumação em "cruz"

print (A * A)

[[ 7 10]
 [15 22]]


In [19]:
#Multiplicação Indice a Indice

print(np.multiply(A,A))

[[ 1  4]
 [ 9 16]]


## Inversa

In [20]:
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [21]:
from numpy.linalg import inv

In [22]:
print(inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


### Transposta

In [23]:
print(A.T)

[[1 3]
 [2 4]]
