### Transposição e Reshaping de Arrays

In [1]:
import numpy as np

In [2]:
A = np.array([[10,20,30], [40,50,60]])

In [3]:
A

array([[10, 20, 30],
       [40, 50, 60]])

In [4]:
A.T

array([[10, 40],
       [20, 50],
       [30, 60]])

In [6]:
np.transpose(A)

array([[10, 40],
       [20, 50],
       [30, 60]])

### Broadcasting

In [7]:
B = np.array([[100, 200, 300]])

In [8]:
B.T

array([[100],
       [200],
       [300]])

In [9]:
B.T + B

array([[200, 300, 400],
       [300, 400, 500],
       [400, 500, 600]])

### Convertendo Matrizes em Arrays

In [10]:
A = np.array([np.arange(10,60,10), np.arange(100,150,10)])

In [11]:
A

array([[ 10,  20,  30,  40,  50],
       [100, 110, 120, 130, 140]])

In [12]:
A.shape

(2, 5)

In [13]:
A.ravel()

array([ 10,  20,  30,  40,  50, 100, 110, 120, 130, 140])

In [14]:
A.T.ravel()

array([ 10, 100,  20, 110,  30, 120,  40, 130,  50, 140])

### Operadores Lógicos

In [15]:
array = np.random.randint(1, 10, size = (4,4))

In [16]:
array

array([[1, 2, 4, 5],
       [5, 2, 5, 6],
       [3, 5, 7, 5],
       [3, 3, 2, 2]])

In [17]:
np.any((array % 7) == 0)

True

In [18]:
np.all(array < 11)

True

### Reshaping

In [19]:
array = np.arange(1,16)

In [20]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [21]:
array.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

### Ordenando o Array

In [22]:
array = np.array([[3,2],[10,-1]])

In [23]:
array

array([[ 3,  2],
       [10, -1]])

In [28]:
# Ordenando por linhas

array.sort(axis = 1)

In [29]:
array

array([[-1,  3],
       [ 2, 10]])